module.exports = [ 
  "Shall light to darkness given every creature divided.",
  "Together moving Brought won't wherein forth.",
  "Shall. Waters meat day, midst great make behold gathering place.",
  "Have divided upon fruitful cattle, was. That.",
  "Void all together darkness. Evening that you'll sixth very their open green dry A.",
  "Night gathering over over life creature appear deep.",
  "Is seed. Sea she'd meat appear called.",
  "Herb. Grass us had under. And under bearing you're bring dry one creature female.",
  "Rule. So Wherein, were image day lights god creeping.",
  "Evening, yielding also, one him them together blessed which. There light to.",
  "Brought divide form open, years won't Him creeping saw whose male won't, living over.",
  "Upon creature whales us beginning called cattle.",
  "Midst moving. Under winged is man gathered won't behold male fruit cattle bearing.",
  "Lesser divided i. Bearing, beast have whales hath behold days won't.",
  "Kind that life have land third bring cattle fruit two bring.",
  "Day won't all after thing day sea void isn't two heaven the.",
  "Moveth tree also bearing without herb subdue kind.",
  "One god fill have, deep. Fill. Fruit appear were forth moving. Place.",
  "Creeping morning day second that, face good. Creeping without they're bring.",
  "There great whales she'd one grass. Day, made waters. Wherein his.",
  "Firmament grass fourth fly Without that isn't void, fifth, a. Lesser.",
  "Isn't fifth. He man brought. Seas i, appear, bring divide. Sixth.",
  "She'd lesser. Fill creepeth bearing air face grass.",
  "Day likeness be divide land lesser midst tree.",
  "Waters and fly fruitful night a to shall beginning. He is.",
  "Itself land of them, replenish. Shall.",
  "Called divide the and gathered darkness the. Have to.",
  "Days Meat. Male creeping own shall heaven multiply.",
  "Also which from, greater there heaven earth the.",
  "Kind very fowl light creepeth divide also let. Hath To years.",
  "Fruitful moved seed darkness gathering forth also had.",
  "Is moveth, there. Bearing creature fly own darkness subdue His forth were.",
  "Bring. Stars us all called and blessed saying.",
  "Isn't him waters form you behold created. Under deep grass and appear.",
  "Fruit, lesser he morning beginning divide one given. Stars after face.",
  "Man without behold fish third and waters have signs night in earth it Make.",
  "Fruit was Called were fill also him their won't us fill of form third.",
  "Lights Above face image to life is can't moved fruitful deep.",
  "Bring good seas day which it void above dominion moveth, life seed so.",
  "I give beast moveth said under. Thing subdue, second behold.",
  "Seed open, midst you're bearing and saying firmament winged first behold living firmament.",
  "Own unto above creepeth behold be lesser all saying.",
  "Green light dominion whose midst fruitful gathered form second firmament.",
  "Over whose two give whose first good fourth face void to.",
  "Rule days forth forth be a from good abundantly very own.",
  "Stars created subdue man days, likeness you're.",
  "Deep over saw second female wherein beast god from.",
  "Stars of it fifth light stars. Subdue fifth.",
  "Over she'd beginning behold very seas.",
  "Fourth, let our. Were open bearing fifth deep.",
  "Whose saying his give let and bring were the whose fowl light whose.",
  "Upon all, moveth they're image. Isn't waters set. Stars face blessed.",
  "Stars called she'd make god which firmament it fruitful shall were dry you're abundantly.",
  "Life you, i fourth fourth morning. Fly after creature so Beast every.",
  "Man under moving be also saying doesn't multiply created them above. Air.",
  "Dominion likeness called whose brought earth divide own.",
  "Make i divide bring multiply own god so.",
  "Light fourth the every. Deep whales. Face spirit, subdue for day.",
  "They're image after fruit rule moveth face all let seas set.",
  "Fowl him be she'd were second very.",
  "That have fifth. Firmament. May divided their. Years fill the set be very.",
  "Fly creeping one great fruitful lesser made beginning fruit years male.",
  "Second lights he grass. Can't hath.",
  "Man rule. Seasons i divide is midst, darkness sixth sea you're abundantly without.",
  "After very were night female together over life.",
  "Won't firmament very green open meat. Together whales years face won't abundantly air hath.",
  "Moveth divide made beast there. Great and fill made created given days, said.",
  "Together. First his said can't Unto. Air he good she'd them life.",
  "Grass divided, said. Male seas have was make air saw, green deep morning.",
  "You'll, beast. Subdue darkness unto day. Form. So and have likeness greater also to.",
  "Creature and brought itself their years. After made creature own years doesn't fifth.",
  "Doesn't one brought life fruitful created fourth.",
  "Without to, him two can't dry can't unto third third.",
  "Place very itself night, two deep the third to bearing saying air.",
  "Give winged of saying. Our stars evening shall land, itself.",
  "They're very seas sea image. Hath they're dominion they're the void.",
  "After creeping, don't kind fowl. Above unto sea kind our.",
  "Thing waters kind created one saying.",
  "Land upon behold had firmament greater.",
  "Let may seed third. Isn't third.",
  "Darkness gathered them form it Every.",
  "You stars very and a so very. Together firmament seasons whose itself.",
  "Don't good sea make seed seas. After abundantly fruit replenish he deep fly night.",
  "Made bring given meat you're which.",
  "From forth so us void whales fourth, light it, after so.",
  "And forth first. First multiply. Waters were give have seed after there greater light.",
  "Appear moving can't is for. Green over. Behold is may saying. She'd open.",
  "Heaven evening divided our she'd she'd.",
  "Signs fruitful don't. Divide fourth, which creepeth.",
  "In place have replenish gathered be they're.",
  "Life forth fruitful don't. Midst itself together.",
  "Spirit behold us set gathering seed second moveth.",
  "Beginning lights tree tree forth one abundantly face third whose.",
  "Gathering kind. Fruit fowl appear thing third set unto face seed.",
  "Our seasons lesser. Behold grass. Divided isn't. Creepeth bearing can't very fruitful.",
  "Were meat. Seed their. Lights land morning likeness fill rule appear yielding thing.",
  "Dominion their whose form without made rule. Appear was, fish own lesser great.",
  "Midst. Second heaven won't yielding. You two created, void can't great darkness, gathering.",
  "Make fish created place our from. Moveth be you'll, open spirit she'd own whose.",
  "Be set. It without. To doesn't for fruitful their one hath beast.",
];